vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter
    - almenon.arepl
    - hbenl.vscode-test-explorer
    - ms-python.python
    - hbenl.test-adapter-converter
    - ms-toolsai.jupyter
